version: '2.0'

services:
  web:
    build:
      context: .
    command: gunicorn todo_django.wsgi:application --bind 0.0.0.0:8000 --workers=4
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: todo_django
      POSTGRES_PASSWORD: postgres

